### ISSUE TITLE
Image from URL not loading

### ISSUE THREAD

**Issue by kvarela** [florent37/DaVinci#7]
Thanks for putting this together. I've been struggling with getting assets to transfer over from phone to Wear and this looked like a great solution. Alas, however, I can't get it to work. I'm calling it in my wear Activity like this:

DaVinci.with(MainWearActivity.this).load("https://d1ghufavkue0e7.cloudfront.net/cache/81/2f/812f6daa34dd1c9c29b5709c5b686f30.jpg").into(mImageViewPhoto);

This is the output I see in logcat:

10-30 12:28:43.266    9893-9893/com.coffeemeetsbagel D/com.github.florent37.davinci.DaVinci﹕ ====================================
10-30 12:28:43.302   9893-11774/com.coffeemeetsbagel D/com.github.florent37.davinci.DaVinci﹕ load(https://d1ghufavkue0e7.cloudfront.net/cache/81/2f/812f6daa34dd1c9c29b5709c5b686f30.jpg)
10-30 12:28:43.302   9893-11774/com.coffeemeetsbagel D/com.github.florent37.davinci.DaVinci﹕ key https://d1ghufavkue0e7.cloudfront.net/cache/81/2f/812f6daa34dd1c9c29b5709c5b686f30.jpg = /davinci/-1310403522 key=-558596910
10-30 12:28:43.302   9893-11774/com.coffeemeetsbagel D/com.github.florent37.davinci.DaVinci﹕ key for https://d1ghufavkue0e7.cloudfront.net/cache/81/2f/812f6daa34dd1c9c29b5709c5b686f30.jpg is -558596910
10-30 12:28:43.302   9893-11774/com.coffeemeetsbagel D/com.github.florent37.davinci.DaVinci﹕ bitmap https://d1ghufavkue0e7.cloudfront.net/cache/81/2f/812f6daa34dd1c9c29b5709c5b686f30.jpg from lruCache [-558596910] null
10-30 12:28:43.302   9893-11774/com.coffeemeetsbagel D/com.github.florent37.davinci.DaVinci﹕ try to load from disk cache -558596910
10-30 12:28:43.302   9893-11774/com.coffeemeetsbagel D/com.github.florent37.davinci.DaVinci﹕ bitmap https://d1ghufavkue0e7.cloudfront.net/cache/81/2f/812f6daa34dd1c9c29b5709c5b686f30.jpg from diskLruCache null
10-30 12:28:43.302   9893-11774/com.coffeemeetsbagel D/com.github.florent37.davinci.DaVinci﹕ bitmap from cache null for https://d1ghufavkue0e7.cloudfront.net/cache/81/2f/812f6daa34dd1c9c29b5709c5b686f30.jpg
10-30 12:28:43.302   9893-11774/com.coffeemeetsbagel D/com.github.florent37.davinci.DaVinci﹕ image https://d1ghufavkue0e7.cloudfront.net/cache/81/2f/812f6daa34dd1c9c29b5709c5b686f30.jpg not available in the cache, trying to download it
10-30 12:28:43.302   9893-11774/com.coffeemeetsbagel D/com.github.florent37.davinci.DaVinci﹕ loadImage https://d1ghufavkue0e7.cloudfront.net/cache/81/2f/812f6daa34dd1c9c29b5709c5b686f30.jpg send request to smartphone -1310403522

Image never comes in. Any help appreciated!

**Comment by mvyas85** [comment]
Found out these library is too out of date.. 

That library is using an older version of the Google Play Services SDK and it still relies on the fact that GoogleApiClient class is an interface... So it wont work if we are using hire version of google services in our application :(

I am also having trouble loading image in werable adapter's background -

getBackgroundForRow() method call - 
                                                 --------- beginning of crash
com.**_.**_.wear E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.**_.**_.wear, PID: 8548
                                                 java.lang.IncompatibleClassChangeError: Found class com.google.android.gms.common.api.GoogleApiClient, but interface was expected (declaration of 'com.google.android.gms.common.api.GoogleApiClient' appears in /data/app/com.**_.**_.wear-1/base.apk)
                                                     at com.github.florent37.davinci.DaVinci.<init>(DaVinci.java:99)
                                                     at com.github.florent37.davinci.DaVinci.init(DaVinci.java:111)
                                                     at com.github.florent37.davinci.DaVinci.with(DaVinci.java:121)
                                                     at com.**_.**_.wear.adapter.OffersAdapter.getBackgroundForRow(OffersAdapter.java:78)
                                                     at android.support.wearable.view.BackgroundController$1.create(BackgroundController.java:84)
                                                     at android.support.wearable.view.BackgroundController$1.create(BackgroundController.java:81)
                                                     at android.support.v4.util.LruCache.get(LruCache.java:99)
                                                     at android.support.wearable.view.BackgroundController.updateBaseLayer(BackgroundController.java:230)
                                                     at android.support.wearable.view.BackgroundController.updateBackgrounds(BackgroundController.java:201)
                                                     at android.support.wearable.view.BackgroundController.onPageScrolled(BackgroundController.java:173)
                                                     at android.support.wearable.view.GridViewPager.onPageScrolled(GridViewPager.java:1606)
                                                     at android.support.wearable.view.GridViewPager.pageScrolled(GridViewPager.java:1564)
                                                     at android.support.wearable.view.GridViewPager.scrollToItem(GridViewPager.java:724)
                                                     at android.support.wearable.view.GridViewPager.onLayout(GridViewPager.java:1491)
                                                     at android.view.View.layout(View.java:17519)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                     at android.support.wearable.view.BoxInsetLayout.onLayout(BoxInsetLayout.java:315)
                                                     at android.view.View.layout(View.java:17519)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                     at android.view.View.layout(View.java:17519)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1737)
                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1581)
                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1490)
                                                     at android.view.View.layout(View.java:17519)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                     at com.android.internal.policy.DecorView.onLayout(DecorView.java:725)
                                                     at android.view.View.layout(View.java:17519)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2351)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2078)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6305)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
system_process W/ActivityManager:   Force finishing activity
